### ISSUE TITLE
AntSpace or AntButton ??

### ISSUE THREAD

**Issue by PvlD** [uxsoft/Fable.AntD#11]
type **AntSpace**() =
    inherit AntElement<**AntButton**>(ofImport "Space" "antd")

**Comment by uxsoft** [comment]
Good catch! Fixed in [https://github.com/uxsoft/Fable.AntD/commit/00862bcaa2320d199d549b76ddf2bd9621ffa585](https://github.com/uxsoft/Fable.AntD/commit/00862bcaa2320d199d549b76ddf2bd9621ffa585)
