### ISSUE TITLE
AntSlider is Importing the Wrong Component

### ISSUE THREAD

**Issue by ShaneMasuda** [uxsoft/Fable.AntD#30]
Howdy,

AntSlider is importing Avatar rather than Slider.

Additionally, could you change defaultValue to be a float rather than a float []?

Thanks in advance,

Shane

**Comment by uxsoft** [comment]
Hi,

Good catch, thanks! I published a new version which should address your issue, let me know if it works for you.

https://github.com/uxsoft/Fable.AntD/commit/a4d813f0c41185fc47866f4c2f0eb85dd013d5b7

**Comment by ShaneMasuda** [comment]
Great work. Thank you for addressing the issue so quickly!
