### ISSUE TITLE
Issues with Input and InputNumber

### ISSUE THREAD

**Issue by ShaneMasuda** [uxsoft/Fable.AntD#34]
Howdy again,

A few quick issues:

The onChange member of Input should probably take a (string -> unit) rather than a (browser event -> unit).

Similarly, the onPressEnter member of Input and InputNumber should probably take (string -> unit) and (float -> unit) respectively.

Overall I’m amazed at what you’ve done, thank you for the great work!

Shane

**Comment by uxsoft** [comment]
Hi,

Even though https://ant.design/components/input/ don't give much info about this, in practice you get back a Browser Event. You can access the value through `e.Value`. 

```fsharp
AntInput()
    .prefix(AntIcons.MailOutlined.style(grayedOut).[[]])
    .onChange(fun e -> setModel (fun s -> { s with Email = e.Value }))
    .placeholder("Email")
    .[[]]
```

I could change the behavior in the bindings but that would mean the behavior wouldn't be consistent with the javascript version and in some cases the browser event might be useful.

**Comment by ShaneMasuda** [comment]
You make a solid point. I'm closing this now, thanks!
